all:
	cat pre.js CharacterObject.js ChipImage.js GameGraphicsForApplet.js GameKey.js GameMouse.js GameSoundForApplet.js GlobalFunctions.js IdouGamen.js ImageBuff.js KeyboardMenu.js MainProgram.js MapSystem.js MasaoConstruction.js MasaoJSS.js TagDataBase.js YukaObject.js post.js | uglifyjs -c -o ../Outputs/CanvasMasao.js 
