	var CanvasMasao = {};
	CanvasMasao.CharacterObject = CharacterObject;
	CanvasMasao.GameGraphicsForApplet = GameGraphicsForApplet;
	CanvasMasao.GameKey = GameKey;
	CanvasMasao.GameMouse = GameMouse;
	CanvasMasao.GameSoundForApplet = GameSoundForApplet;
	CanvasMasao.Game = Game;
	CanvasMasao.IdouGamen = IdouGamen;
	CanvasMasao.ImageBuff = ImageBuff;
	CanvasMasao.KeyboardMenu = KeyboardMenu;
	CanvasMasao.MainProgram = MainProgram;
	CanvasMasao.MapSystem = MapSystem;
	CanvasMasao.MasaoConstruction = MasaoConstruction;
	CanvasMasao.TagDataBase = TagDataBase;
	CanvasMasao.YukaObject = YukaObject;
	return CanvasMasao;
}();

var JSMasao = CanvasMasao.Game;
JSMasao.MasaoConstruction = CanvasMasao.MasaoConstruction;
