js=pre.js CharacterObject.js GameGraphics.js GameKey.js GameMouse.js GlobalFunctions.js IdouGamen.js ImageBuff.js KeyboardMenu.js MainProgram.js MapSystem.js MasaoConstruction.js post.js
all:
	cat ${js} | uglifyjs --rename -c -o ../Outputs/CanvasMasao_v28.js
nouglify:
	cat ${js} > ../Outputs/CanvasMasao_v28.js
