	var CanvasMasao = {};
	CanvasMasao.CharacterObject = CharacterObject;
	CanvasMasao.GameGraphics = GameGraphics;
	CanvasMasao.GameKey = GameKey;
	CanvasMasao.GameMouse = GameMouse;
	CanvasMasao.Game = Game;
	CanvasMasao.IdouGamen = IdouGamen;
	CanvasMasao.ImageBuff = ImageBuff;
	CanvasMasao.KeyboardMenu = KeyboardMenu;
	CanvasMasao.MainProgram = MainProgram;
	CanvasMasao.MapSystem = MapSystem;
	CanvasMasao.MasaoConstruction = MasaoConstruction;
	return CanvasMasao;
}(window, document, Math);
