all:
	cat pre.js CharacterObject.js GameGraphics.js GameKey.js GameMouse.js GlobalFunctions.js IdouGamen.js ImageBuff.js KeyboardMenu.js MainProgram.js MapSystem.js MasaoConstruction.js post.js | uglifyjs -c -o CanvasMasao_v28.js 
