name: autoMasaoTest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Git Fetch Latest tag
      run: |
        git fetch --prune --unshallow

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build

    - name: Cache built files
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          dist
        key: ${{ runner.os }}-build-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ matrix.node-version }}-

    - name: Test
      run: |
        npm run test