name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Git Fetch Latest tag
      run: |
        git fetch --prune --unshallow

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci

    - name: Build all
      run: npm run build-all

    - name: Commit build artifacts
      run: |
        git config --local user.name 'GitHub Action'
        git config --local user.email 'action@github.com'
        git checkout master
        git add Outputs/CanvasMasao.js Outputs/CanvasMasao_v28.js Outputs/MasaoKani2.js
        git commit -m "ビルド"
        git push origin master

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: mc_canvas ${{ github.ref_name }}
        draft: true
        prerelease: false

    - name: Upload CanvasMasao.js
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Outputs/CanvasMasao.js
        asset_name: CanvasMasao.js
        asset_content_type: application/javascript

    - name: Upload CanvasMasao_v28.js
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Outputs/CanvasMasao_v28.js
        asset_name: CanvasMasao_v28.js
        asset_content_type: application/javascript

    - name: Upload MasaoKani2.js
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Outputs/MasaoKani2.js
        asset_name: MasaoKani2.js
        asset_content_type: application/javascript